apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: docker-devfile-sample-hello-world-r1pn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: docker-devfile-sample-hello-world-r1pn
    app.kubernetes.io/part-of: test-app-lbbl
  name: docker-devfile-sample-hello-world-r1pn
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: docker-devfile-sample-hello-world-r1pn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: docker-devfile-sample-hello-world-r1pn
    spec:
      containers:
      - image: quay.io/jentesting/build-e2e-vrfm-tenant/test-app-lbbl/docker-devfile-sample-hello-world-r1pn@sha256:d909c9ec8712779b537f51bd84184b0d5e7d7478c3ceaa790f531153668eb498
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
